name: 'Maven CLI For GitHub Actions'
description: 'Use Maven CLI with JDK 8, 11, 14'
inputs:
    lifecycle:
        description: 'Maven lifecycles'
        required: true
        default: 'clean package'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.lifecycle }}
branding:
  icon: 'chevron-right'  
  color: 'orange'
